# Generated by Django 4.0.4 on 2022-04-24 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 4, 24, 8, 0, 26, 203912))),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_robots.robot')),
            ],
        ),
    ]
