# Generated by Django 4.0.4 on 2022-04-18 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 19, 6, 47, 166339)),
        ),
        migrations.AddField(
            model_name='position',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robot',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
