# Generated by Django 4.0.4 on 2022-04-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_robots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='robot',
            new_name='robot_id',
        ),
    ]
