# Generated by Django 4.0.4 on 2022-04-18 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_robots', '0002_position_datetime_position_x_position_y_robot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 19, 6, 54, 709036)),
        ),
    ]
