# Generated by Django 4.0.4 on 2022-04-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_robots', '0002_rename_robot_position_robot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='robot_id',
            new_name='robot',
        ),
    ]
